### ISSUE TITLE
Steps on how to add branches then merge

### ISSUE THREAD

**Issue by alvin-henry** [jrtheking43/test2#1]
![5](https://user-images.githubusercontent.com/93213883/173473114-b3e8412e-b29c-4327-a8aa-3442c32d61d1.png)
![6](https://user-images.githubusercontent.com/93213883/173473115-29e98829-a48a-4052-80af-8d6b1a7c9d34.png)
![7](https://user-images.githubusercontent.com/93213883/173473116-f9afa707-92d8-44e4-8622-ddd201080719.png)
![8](https://user-images.githubusercontent.com/93213883/173473117-10c788f4-aa66-4215-aa7a-177f9e6e0701.png)
![9](https://user-images.githubusercontent.com/93213883/173473119-cb30cd2f-f1b6-46d8-9e14-aa5239f66d11.png)
![10](https://user-images.githubusercontent.com/93213883/173473120-ca73575b-5b88-40ac-a60d-9e91c99b129c.png)
![11](https://user-images.githubusercontent.com/93213883/173473122-d90c663d-2f8a-4af3-986f-e8e674c278b0.png)
![12](https://user-images.githubusercontent.com/93213883/173473109-80d812f9-9ab2-46ba-acd1-c80a87b9c824.png)

**Comment by jrtheking43** [comment]
Issue is fixed

**Comment by alvin-henry** [comment]
Issue is fixed
